services:
  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-fraud
      PGPORT: "5433"
    volumes:
      - ./fraud-data:/var/lib/postgresql/data/fraud
    expose:
    - "5433"
    ports:
    - "5433:5433"
    networks:
      - postgres
    restart: unless-stopped

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-customer
      PGPORT: "5434"
    volumes:
      - ./customer-data:/var/lib/postgresql/data/customer
    expose:
    - "5434"
    ports:
    - "5434:5434"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-notification
      PGPORT: "5435"
    volumes:
      - ./notification-data:/var/lib/postgresql/data/notification
    expose:
      - "5435"
    ports:
      - "5435:5435"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: microservices
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://microservices:password@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: microservices
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: microservices
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mongo-network

networks:
  postgres:
    driver: bridge
  mongo-network:
    driver: bridge

volumes:
  notification-data:
  fraud-data:
  customer-data:
  mongo-data:
  pgadmin: