services:
  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-fraud
      PGPORT: "5433"
    volumes:
      - ./fraud-data:/var/lib/postgresql/data/fraud
    expose:
    - "5433"
    ports:
    - "5433:5433"
    networks:
      - postgres
    restart: unless-stopped

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-customer
      PGPORT: "5434"
    volumes:
      - ./customer-data:/var/lib/postgresql/data/customer
    expose:
    - "5434"
    ports:
    - "5434:5434"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-notification
      PGPORT: "5435"
    volumes:
      - ./notification-data:/var/lib/postgresql/data/notification
    expose:
      - "5435"
    ports:
      - "5435:5435"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: microservices
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://microservices:password@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: microservices
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongo
    networks:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: microservices
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mongo

  eureka-server:
    image: tnoxx/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  apigw:
    image: tnoxx/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: tnoxx/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  fraud:
    image: tnoxx/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  notification:
    image: tnoxx/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  email:
    image: tnoxx/email:latest
    container_name: email
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mongo
    depends_on:
      - zipkin
      - eureka-server
      - mongo
      - rabbitmq

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
  spring:
    driver: bridge

volumes:
  notification-data:
  fraud-data:
  customer-data:
  mongo-data:
  pgadmin: