services:
  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-fraud
      PGPORT: "5430"
    volumes:
      - postgres:/data/postgres-fraud
    expose:
    - "5430"
    ports:
    - "5430:5430"
    networks:
      - postgres
    restart: unless-stopped

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-customer
      PGPORT: "5431"
    volumes:
      - postgres:/data/postgres-customer
    expose:
    - "5431"
    ports:
    - "5431:5431"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: