server:
  port: 8089
  error:
    include-message: always

spring:
  application:
    name: email

  data:
    mongodb:
      authentication-database: admin
      username: microservices
      password: password
      database: email-notification
      port: 27017
      host: localhost


  mail:
    host: smtp.gmail.com
    port: 587
    username: thiagocroza472@gmail.com
    password: guhkvntgaykixmwt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    email-notification: email.notification.queue
  routing-keys:
    internal-email-notification: internal.email.notification.routing-key

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG